apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    meta.helm.sh/release-name: budibase
    meta.helm.sh/release-namespace: budibase
  labels:
    app.kubernetes.io/instance: budibase
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: budibase
    app.kubernetes.io/version: 1.0.48
    helm.sh/chart: budibase-0.2.8
  name: ingress-nginx
  namespace: budibase
spec:
  rules:
    ingress:
      enabled: true
      nginx: true
      className: ""
      annotations: 
        kubernetes.io/ingress.class: nginx
      hosts:
        - host: yourdomain.com
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxy-service
                port:
                  number: 10000 
